ipbus/ipbb

- README.md
- ipbb/commands/__init__.py
- ipbb/commands/dep.py
- ipbb/commands/proj.py
- ipbb/commands/repo.py
- ipbb/commands/sim.py
- ipbb/dep2g/IPCoresSimMaker.py
- test/bin/test_ipbus_internals.sh
- test/bin/test_mp7_noipbus.sh
- test/bin/test_projects.sh
Ipbb updated to use the new public ipbus firmware repository.
> Post ipbus-firmware release merge

- bin/ipbb
> Forgotten click_shell import removed.

- Changelog.md
- ci/setup.yml
- requirements.txt
- setup.py
- venv/scripts/setup_ipbb_venv.sh
Dependency python packages versions now detailed in `requirements.txt`.
`requirements.txt` automatically included in `setup.py`
> Versioned dependencies

- Changelog.md
- setup.py
- src/ipbb/cmds/vivado.py
- src/ipbb/depparser/_depparser_core.py
- src/ipbb/depparser/_pathmaker.py
- src/ipbb/tools/common.py
- src/ipbb/tools/xilinx/vivado_project.py
- venv/scripts/update_requirements.sh
The name of the vivado bitfiule is now aligned to the project name.
Also the bitfile is saved in the `products/` project subfolder
> Bitfile name

- src/ipbb/cmds/sim.py
- src/ipbb/makers/ipcoressim.py
- src/ipbb/makers/modelsimproject.py
- src/ipbb/makers/vivadoproject.py
- src/ipbb/tools/xilinx/vivado_project.py
> Support for xcix files in Vivado

- src/ipbb/cli/proj.py
- src/ipbb/cmds/common.py
- src/ipbb/cmds/proj.py
- src/ipbb/cmds/vivado.py
- src/ipbb/depparser/__init__.py
- src/ipbb/depparser/_fileparser.py
- src/ipbb/depparser/_pathmaker.py
> .d3 and .dep defaults

- src/ipbb/cmds/proj.py
> Fixed automatic top-level dep file resolution in project creation

- ci/tests.yml
Enables ci tess on centos 8 platforms
> Re-enabled centos8 ci tests

- src/ipbb/cmds/ipbus.py
- src/ipbb/depparser/_fileparser.py
- src/ipbb/tools/alien.py
- src/ipbb/tools/xilinx/vivado_console.py
These are a few (minor) changes that are required to make things work on CC8 (with Python3). I won't claim that these are all required changes, but they are enough to make my workflow work again. (And I'm not set up to test outside my workflow, really.)
> Cc8 and python3 fixes

- ci/tests.yml
- src/ipbb/tools/xilinx/vivado_console.py
- src/ipbb/tools/xilinx/vivadohls_console.py
The PR brings the CC7 and Centos 8 Ci tests in alignment.
Closes #88
> Align CC7 and Centos8 tests

- src/ipbb/cli/vivado.py
As the subject suggests, it fixes a bug
Closes #109
> #109: ipbb generate-project cli bug fixed

- ci/github-notifications.yml
- src/ipbb/cmds/schema.py
- src/ipbb/cmds/sim.py
- src/ipbb/cmds/vivado.py
- src/ipbb/cmds/vivadohls.py
> Tweaking schema validation to allow unknowns

- src/ipbb/cmds/dep.py
- src/ipbb/depparser/_fileparser.py
- tests/repogen/pkgAB_issue_133.yml
- tests/scripts/generate-ipbb-repo.py
> #133: Correct default component handling when package != current package

- src/ipbb/cmds/vivado.py
Importing changes from #125 into master.
> Add a few more errors to ipbb vivado check-syntax (#125)

- ci/tests.yml
- src/ipbb/cmds/ipbus.py
- src/ipbb/generators/modelsimproject.py
Adds support for simulation core generation in Vivado 2020.
Also fixes a bug in gendecoders.
> Support for ipcore sim generation with Vivado 2020

- src/ipbb/cli/proj.py
- src/ipbb/cmds/common.py
- src/ipbb/cmds/dep.py
- src/ipbb/cmds/ipbus.py
- src/ipbb/cmds/proj.py
- src/ipbb/cmds/repo.py
- src/ipbb/cmds/sim.py
- src/ipbb/cmds/toolbox.py
- src/ipbb/cmds/vivado.py
- src/ipbb/cmds/vivadohls.py
- src/ipbb/generators/ipcoressim.py
- src/ipbb/generators/modelsimproject.py
- src/ipbb/scripts/programmer.py
- src/ipbb/tools/common.py
- src/ipbb/tools/mentor/sim_batch.py
- src/ipbb/tools/mentor/sim_common.py
- src/ipbb/tools/mentor/sim_console.py
- src/ipbb/tools/xilinx/vivado_common.py
- src/ipbb/tools/xilinx/vivado_console.py
- src/ipbb/tools/xilinx/vivadohls_console.py
- src/ipbb/utils.py
This PRs fixes a remaining issue with IPCores simulation in Vivado 2020
> Update of modelsim workflow to vivado 2020

- src/ipbb/cmds/vivado.py
This branch adds the ability to create SVF files.
User interface:
* SVF files will only be created if the 'vivado.svf_jtagchain_devices' setting is specified
* This should be a two-element tuple, where the first (second) element is the list of devices in the JTAG chain before (after) the target device.
* For example:
* If target FPGA is the only device in the chain: `@vivado.svf_jtagchain_devices = ([], [])`
* If there is a KU15P before the target FPGA: `@vivado.svf_jtagchain_devices = (['-part xcku15p-ffva1760-2-e'], [])`
* The SVF file will be created by `ipbb vivado package`, unless it already exists. (No additional commands created.)
Implementation details:
* SVF files are created by the `_svffile` function, in `cmds/vivado.py`
* TCL commands based on chapter 8 of …
> Draft: Add ability to create SVF files

- src/ipbb/context/__init__.py
> Add missing cprint import in context/__init__.py

- src/ipbb/depparser/__init__.py
- src/ipbb/depparser/_fileparser.py
- src/ipbb/utils/utils.py
> Fixing missing import/cyclic deps (following #162 )

- doc/deptree.md
- setup.py
- src/ipbb/cmds/sim.py
- src/ipbb/cmds/vivado.py
- src/ipbb/context/__init__.py
- src/ipbb/scripts/builder.py
- src/ipbb/tools/mentor/__init__.py
- src/ipbb/tools/xilinx/__init__.py
- src/ipbb/utils/printing.py
- venv/scripts/setup_ipbb_venv.sh
> Fixes several small bugs introduced with 2022c

- src/ipbb/cmds/dep.py
- src/ipbb/depparser/_cmdtypes.py
By implementing proper hashing of DepCommands and SrcCommands
> Fixes duplicate commands
